iconpath='../../data/icons'
humanpath = '../../data/human.jpg'
phecatpath = '../../data/phecat.npy'
datpath = '../../results/Process_missingness'
imgpath = '../../results/Process_missingness/mripc_imputed.csv'
showcasepath = '../../data/Preprocess/showcase.csv'
predpath = "../../results/Disease_diagnosis/pred/"
survpath = "../../results/Disease_diagnosis/surv/"
pripath = "../../results/Disease_diagnosis/pri/"
pripathds = "../../results/Disease_diagnosis/survpri/"
imputepath = "../../results/Disease_diagnosis/impute/"
scpath = "../../results/Disease_diagnosis/sc/"
survscpath = "../../results/Disease_diagnosis/survsc/"
imppath = '../../results/Disease_diagnosis/imp/'
survimppath = '../../results/Disease_diagnosis/survimp/'
lgbpath = '../../results/Disease_diagnosis/lgb/'
xgbpath = '../../results/Disease_diagnosis/xgb/'
rfpath = '../../results/Disease_diagnosis/rf/'
phecodespath = "../../data/phecode.csv"
phedefpath = "../../data/phecode_definitions1.2.csv"
trainpath = "../disease_diagnosis/"

eventpath = "../../results/Preprocess/y/0-1.npy"
timepath = "../../results/Preprocess/y/cox.npy"
bchpath = "../../results/Plot/temp/bch.csv"

temppath = "../../results/Plot/temp/"
outputpath = "../../results/Plot/output/"
numericpath = "../../results/Plot/numeric_result/"